stages:

  preprocess:
    cmd: python src/preprocess.py
    deps:
    - src/preprocess.py
    - data/raw/Titanic-Dataset.csv
    outs:
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/processed/X_train.csv
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - models/model.pkl
