name: CD
#child workflow
on:
  workflow_call:
    inputs:
      image_sha_id:
        required: true
        type: string
    secrets:
      CREDS:
        required: true
      AZURE_WEBAPP_NAME:
        required: true
      DOCKER_USERNAME:
        required: true
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Azure Login
      uses: Azure/login@v3
      with:
        creds: ${{ secrets.CREDS }}
    - name: Deploy to Azure Web App Container
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        images: ${{ secrets.DOCKER_USERNAME }}/mlops-app:${{inputs.image_sha_id}}